{{- if eq .Values.couchdb.persistentVolume.storageClass "gp3" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
parameters:
  type: gp3
provisioner: ebs.csi.eks.amazonaws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}   