{{- if .Values.baserow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convertigo.fullname" . }}-br
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}-br
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "convertigo.selectorLabels" . | nindent 6 }}-br
  template:
    metadata:
      {{- with .Values.podAnnotations }}-br
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "convertigo.selectorLabels" . | nindent 8 }}-br
    spec:
      serviceAccountName: {{ include "convertigo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: 
        - name : br-data
          persistentVolumeClaim:
            claimName: {{ include "convertigo.fullname" . }}-br-workspace                   
      containers:
        - name: {{ .Chart.Name }}-br
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "baserow/baserow:1.30.1"
          volumeMounts:
            - name: br-data
              mountPath: /baserow/data
          env:
            - name: BASEROW_PUBLIC_URL
              value: https://baserow.service.rhs.zz
            - name: BASEROW_EXTRA_ALLOWED_HOSTS
              value: 192.168.0.2
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end }}                