apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "convertigo.fullname" . }}-c8o-workspace
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.workspace.persistentVolume.size }}"
{{- if .Values.workspace.persistentVolume.storageClass }}
{{- if (eq "-" .Values.workspace.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.workspace.persistentVolume.storageClass }}"
{{- end }}    
{{- end }}       