{{- if .Values.couchdb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "convertigo.fullname" . }}-cdb-workspace
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- range (default (list "ReadWriteOnce") .Values.couchdb.accessModes) }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: "{{ .Values.couchdb.persistentVolume.size }}"
{{- if .Values.couchdb.persistentVolume.storageClass }}
{{- if (eq "-" .Values.couchdb.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.couchdb.persistentVolume.storageClass }}"
{{- end }}  
{{- end }}        
{{- end }}
