{{- $redisPassword := include "convertigo.sessionRedisPassword" . -}}
{{- if and .Values.sessionStore.enabled (eq .Values.sessionStore.mode "redis") .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "convertigo.fullname" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "convertigo.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/name: {{ include "convertigo.fullname" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convertigo.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "convertigo.fullname" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "convertigo.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convertigo.fullname" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "convertigo.fullname" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "convertigo.chart" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            - "--save"
            - "60"
            - "1"
            - "--appendonly"
            - "no"
          {{- if and .Values.redis.auth.enabled $redisPassword }}
            - "--requirepass"
            - "{{ $redisPassword }}"
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "convertigo.fullname" . }}-redis
          {{- else }}
          emptyDir: {}
          {{- end }}

{{- if .Values.redis.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "convertigo.fullname" . }}-redis
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
{{- end }}
{{- end }}
