apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}-br
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}-br
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http-backend
  selector:
    {{- include "convertigo.selectorLabels" . | nindent 4 }}-br
