apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "convertigo.selectorLabels" . | nindent 4 }}
