{{- if .Values.timescaledb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}-timescaledb
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}-timescaledb
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    {{- include "convertigo.selectorLabels" . | nindent 4 }}-timescaledb
{{- end }}       
