apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}-cdb
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}-cdb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5984
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "convertigo.selectorLabels" . | nindent 4 }}-cdb
