name: Publish Helm Chart to Amazon ECR Public

on:
  push:
    branches:
      - master
    paths:
      - "//**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin public.ecr.aws

      - name: Package Helm Chart
        run: |
          helm package stable
          ls -l *.tgz

      - name: Push Helm Chart to Amazon ECR Public
        run: |
          helm push convertigo-8.3.1.tgz oci://public.ecr.aws/m4y9m8m1
