name: Publish Helm Chart to Amazon ECR Public

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Helm Chart
        run: |
          cd stable/convertigo 
          helm version
          helm package .
          ls -l *.tgz

      - name: Push Helm Chart to Amazon ECR Public
        run: |
          # Find the latest `convertigo-x.y.z.tgz` package
          cd stable/convertigo
          LATEST_CHART=$(ls -v convertigo-*.tgz | tail -n 1)        

          aws ecr-public get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin public.ecr.aws
          helm push "$LATEST_CHART" oci://public.ecr.aws/m4y9m8m1
          helm registry logout public.ecr.aws

#      - name: Push Helm Chart to Amazon ECR Marketplace
#        run: |
#          # We need to enable the OCI experimental feature in Helm
#          export HELM_EXPERIMENTAL_OCI=1
#
#          # Login to Amazon ECR
#          echo "Login to Amazon Marketplace ECR..."          
#          aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin 709825985650.dkr.ecr.us-east-1.amazonaws.com
#
#          # Push the chart to Amazon ECR Convertigo-SA Marketplace repository
#          cd stable/convertigo
#          echo "Pushing Helm Chart to Amazon ECR..."          
#          helm push convertigo-8.3.2.tgz  oci://709825985650.dkr.ecr.us-east-1.amazonaws.com/convertigo-sa

      - name: Push Helm Chart to Amazon S3
        run: |
          # Find the latest `convertigo-x.y.z.tgz` package
          cd stable/convertigo
          LATEST_CHART=$(ls -v convertigo-*.tgz | tail -n 1)
          aws s3 cp "$LATEST_CHART" s3://convertigo-helm-charts/
          helm repo index --url https://convertigo-helm-charts.s3.amazonaws.com/  .
          aws s3 cp index.yaml s3://convertigo-helm-charts/
          aws s3 cp artifacthub-repo.yml s3://convertigo-helm-charts/
